Repository Lucaszioli/Trabalho-Final-PDS2, pull requests merged in 2024-06, with the labels that each got.

#1 feat: Commit inicial iniciando as classes Jogador, Monstrinho e Ataque com os atributos e metodos iniciais (a serem criados mais a medida que receber)
  HPPs/Ataque.hpp
  HPPs/Jogador.hpp
  HPPs/Monstrinho.hpp
  HPPs/Treinador.hpp
Labels: enhancement

#4 Update attack data in CSV file
  CSVs/Ataques.csv
  HPPs/Ataque.hpp
Labels: enhancement

#5 Henrique-Dias
  CPPs/Bot.cpp
  CPPs/Jogador.cpp
  CPPs/Treinador.cpp
  HPPs/Bot.hpp
  HPPs/Jogador.hpp
  HPPs/Treinador.hpp
Labels: enhancement

#7 Add attack hit verification and update damage method
  CPPs/Ataque.cpp
  HPPs/Ataque.hpp
Labels: documentation, enhancement

#9 refactor: altera o método checarAcerto e causarDano para o método fazerAtaque
  CPPs/Ataque.cpp
  HPPs/Ataque.hpp
Labels: enhancement

#11 Refactor attack quantity handling
  CPPs/Ataque.cpp
  HPPs/Ataque.hpp
Labels: enhancement

#13 Malu
  CPPs/Monstrinho.cpp
  CSVs/Monstrinhos.csv
  HPPs/Monstrinho.hpp
Labels: documentation, enhancement

#14 add tier/ separa os tipos
  CPPs/Monstrinho.cpp
  CSVs/Monstrinhos.csv
  HPPs/Monstrinho.hpp
Labels: enhancement

#17 Henrique-Dias
  CPPs/Jogador.cpp
Labels: enhancement

#19 Malu
  CPPs/Monstrinho.cpp
  HPPs/Ataque.hpp
  HPPs/Monstrinho.hpp
Labels: enhancement

#22 "Implement attack effectiveness table and fix attack creation bug"
  CPPs/Ataque.cpp
  CPPs/Monstrinho.cpp
  HPPs/Ataque.hpp
  HPPs/Monstrinho.hpp
Labels: enhancement

#23 Muda Cmake e configura itens para modelo sem ponteiro
  .gitignore
  CPPs/Ataque.cpp
  CPPs/Estamina.cpp
  CPPs/Jogador.cpp
  CPPs/Monstrinho.cpp
  build/CMakeCache.txt
  build/CMakeFiles/3.22.1/CMakeCCompiler.cmake
  build/CMakeFiles/3.22.1/CMakeCXXCompiler.cmake
  build/CMakeFiles/3.22.1/CMakeDetermineCompilerABI_C.bin
  build/CMakeFiles/3.22.1/CMakeDetermineCompilerABI_CXX.bin
  build/CMakeFiles/3.22.1/CMakeSystem.cmake
  build/CMakeFiles/3.22.1/CompilerIdC/CMakeCCompilerId.c
  build/CMakeFiles/3.22.1/CompilerIdCXX/CMakeCXXCompilerId.cpp
  build/CMakeFiles/CMakeDirectoryInformation.cmake
  build/CMakeFiles/CMakeOutput.log
  build/CMakeFiles/Makefile.cmake
  build/CMakeFiles/Makefile2
  build/CMakeFiles/Monstrinhos.dir/DependInfo.cmake
  build/CMakeFiles/Monstrinhos.dir/build.make
  build/CMakeFiles/Monstrinhos.dir/cmake_clean.cmake
  build/CMakeFiles/Monstrinhos.dir/compiler_depend.internal
  build/CMakeFiles/Monstrinhos.dir/compiler_depend.make
  build/CMakeFiles/Monstrinhos.dir/compiler_depend.ts
  build/CMakeFiles/Monstrinhos.dir/depend.make
  build/CMakeFiles/Monstrinhos.dir/flags.make
  build/CMakeFiles/Monstrinhos.dir/link.txt
  build/CMakeFiles/Monstrinhos.dir/progress.make
  build/CMakeFiles/TargetDirectories.txt
  build/CMakeFiles/cmake.check_cache
  build/CMakeFiles/progress.marks
  build/Makefile
  build/Monstrinhos
  build/cmake_install.cmake
Labels: enhancement

#28 feat: :sparkles: Ao fazer um ataque, confere se o inimigo foi derrotado e seta a vida dele em 0
  CPPs/Ataque.cpp
Labels: enhancement

#29 Adiciona testes de Ataque
  Tests/Ataques.test.cpp
Labels: enhancement

#30 Matheus gregor
  CPPs/Ataque.cpp
  CPPs/Bot.cpp
  CPPs/Jogador.cpp
  CPPs/Jogo.cpp
  CPPs/Monstrinho.cpp
  CPPs/Treinador.cpp
  HPPs/Bot.hpp
  HPPs/Jogador.hpp
  HPPs/Jogo.hpp
  HPPs/Monstrinho.hpp
  HPPs/Treinador.hpp
  build/CMakeFiles/Progress/1
  build/CMakeFiles/Progress/2
  build/CMakeFiles/Progress/3
  build/CMakeFiles/Progress/4
  build/CMakeFiles/Progress/count.txt
  principal/main.cpp
Labels: bug, enhancement

#34 fix: Conserta erro de final de jogo
  CPPs/Jogador.cpp
  CPPs/Jogo.cpp
Labels: enhancement

#35 Henrique-Dias
  CPPs/Jogador.cpp
  CPPs/Jogo.cpp
Labels: enhancement

#36 feat: Criação e configuração do arquivo Doxyfile para utilização do D…
  Doxyfile
Labels: documentation, enhancement

#39 Update do README
  README.md
Labels: documentation

#38 Adiciona testes e muda velocidade da interação ataques
  CPPs/Jogo.cpp
  CPPs/Monstrinho.cpp
  HPPs/Cura.hpp
  HPPs/Revive.hpp
  Tests/Ataques.test.cpp
  Tests/Bot.test.cpp
  Tests/CMakeLists.txt
  Tests/Itens.test.cpp
  Tests/Jogador.test.cpp
  Tests/Jogo.test.cpp
  Tests/Monstrinho.test.cpp
  Tests/Monstrinhos.test.cpp
  Tests/Treinador.test.cpp
Labels: enhancement

#41 fix: Conserta erro gerado por uso de string em um input de escolha int
  CPPs/Estamina.cpp
  CPPs/Jogo.cpp
Labels: bug, enhancement
